[package]
name = "describe-video-gst"
version = "0.1.0"
edition = "2024"

[dependencies]
gst = { version = "0.17", package = "gstreamer" }
gst-app = { version = "0.17", package = "gstreamer-app" }
gst-video = { version = "0.17", package = "gstreamer-video" }
image = "0.25.6"

[profile.dev]
debug = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

debug = false
strip = true
