[package]
name = "describe-video"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
ndarray = "0.16.1"
num-traits = "0.2.19"
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
video-rs = { version = "0.10.3", features = ["ndarray"] }
