[package]
name = "describe-video"
version = "0.2.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
image = "0.25.6"
log = "0.4.27"
ndarray = "0.16.1"
num-traits = "0.2.19"
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
video-rs = { version = "0.10.3", features = ["ndarray"] }

[dev-dependencies]
hoox = "0.3.0"

[profile.dev]
debug = false

[profile.release]
debug = false
strip = true
