name: security audit
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo +nightly audit --target x86_64-unknown-linux-gnu
