name: Run tests

on:
  push:

jobs:
  build:
    name: run-tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Install libav/libsw
        run:
        | sudo apt install -y libavcodec-dev libavformat-dev libswscale-dev libavfilter-dev libavdevice-dev

      - name: Test
        run: cargo test --target x86_64-unknown-linux-gnu
